export const styles = {
  app: {
    minHeight: "100vh",
    position: "relative",
    isolation: "isolate",
    display: "flex",
    background: "transparent",
    color: "var(--text-primary)",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "SF Pro Text", "SF Pro Display", system-ui, sans-serif',
  },

  sidebar: {
    width: 276,
    height: "calc(100vh - 32px)",
    margin: 16,
    padding: 14,
    position: "sticky",
    top: 16,
    zIndex: 20,
    display: "flex",
    flexDirection: "column",
    gap: 14,
    border: "1px solid var(--glass-border)",
    borderRadius: 28,
    background: "var(--glass-navigation)",
    boxShadow: "var(--shadow-navigation)",
    backdropFilter: "blur(24px) saturate(145%)",
    WebkitBackdropFilter: "blur(24px) saturate(145%)",
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: 11,
    border: "1px solid rgba(255,255,255,0.36)",
    borderRadius: 18,
    background: "rgba(255,255,255,0.2)",
  },
  brandIcon: {
    width: 38,
    height: 38,
    display: "grid",
    placeItems: "center",
    border: "1px solid var(--glass-highlight)",
    borderRadius: 14,
    background: "var(--glass-control)",
    boxShadow:
      "0 8px 22px rgba(75,49,91,0.12), inset 0 1px 0 rgba(255,255,255,0.82)",
  },
  brandTitle: { fontWeight: 720, fontSize: 14, letterSpacing: "-0.01em" },
  brandSub: { marginTop: 1, fontSize: 12, color: "var(--text-muted)" },

  nav: { display: "flex", flexDirection: "column", gap: 7 },
  navIcon: {
    width: 24,
    height: 24,
    display: "inline-grid",
    placeItems: "center",
    flexShrink: 0,
    borderRadius: 8,
    background: "rgba(255,255,255,0.24)",
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 11px",
    border: "1px solid transparent",
    borderRadius: 14,
    background: "transparent",
    color: "var(--text-primary)",
    cursor: "pointer",
    fontSize: 14,
    textAlign: "left",
  },
  navItemActive: {
    border: "1px solid rgba(255,255,255,0.28)",
    background: "var(--accent-gradient)",
    color: "#ffffff",
    boxShadow:
      "0 10px 28px rgba(111,29,53,0.24), inset 0 1px 0 rgba(255,255,255,0.24)",
  },

  sidebarFooter: {
    marginTop: "auto",
    padding: 13,
    border: "1px solid rgba(255,255,255,0.46)",
    borderRadius: 18,
    background: "rgba(255,255,255,0.3)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.54)",
  },
  tipTitle: { marginBottom: 4, fontSize: 12, fontWeight: 700 },
  tipText: { color: "var(--text-muted)", fontSize: 12, lineHeight: 1.35 },

  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" },
  header: {
    margin: "16px 16px 0 0",
    padding: "19px 24px",
    position: "relative",
    zIndex: 10,
    border: "1px solid var(--glass-border)",
    borderRadius: 24,
    background: "var(--glass-navigation)",
    boxShadow: "var(--shadow-soft)",
    backdropFilter: "blur(22px) saturate(140%)",
    WebkitBackdropFilter: "blur(22px) saturate(140%)",
  },
  pageTitle: { margin: 0, fontSize: 22, fontWeight: 780, letterSpacing: "-0.025em" },
  pageSubtitle: { marginTop: 4, color: "var(--text-muted)", fontSize: 12 },

  content: { width: "100%", padding: "16px 16px 34px 0" },
  stack: { display: "flex", flexDirection: "column", gap: 16 },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 },

  block: {
    position: "relative",
    padding: 18,
    border: "1px solid var(--glass-border)",
    borderRadius: 24,
    background: "var(--glass-card)",
    boxShadow: "var(--shadow-card)",
    backdropFilter: "blur(20px) saturate(138%)",
    WebkitBackdropFilter: "blur(20px) saturate(138%)",
  },
  blockTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  blockTitle: { margin: 0, color: "var(--text-primary)", fontSize: 13, fontWeight: 720 },
  sectionTitle: { display: "inline-flex", alignItems: "center", gap: 7 },

  p: { color: "var(--text-secondary)", fontSize: 13, lineHeight: 1.55 },
  quote: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    color: "var(--text-secondary)",
    fontSize: 13,
    lineHeight: 1.55,
  },
  emptyMessage: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: "var(--text-secondary)",
    fontSize: 13,
  },
  statusWithIcon: { display: "inline-flex", alignItems: "center", gap: 5 },
  list: {
    margin: 0,
    paddingLeft: 18,
    color: "var(--text-secondary)",
    fontSize: 13,
    lineHeight: 1.7,
  },

  textarea: {
    width: "100%",
    padding: 12,
    border: "1px solid var(--control-border)",
    borderRadius: 16,
    outline: "none",
    resize: "vertical",
    background: "var(--glass-control)",
    color: "var(--text-primary)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.62)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    fontSize: 13,
  },
  input: {
    flex: 1,
    width: "100%",
    padding: "10px 12px",
    border: "1px solid var(--control-border)",
    borderRadius: 14,
    outline: "none",
    background: "var(--glass-control)",
    color: "var(--text-primary)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.64)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    fontSize: 13,
  },
  inlineInput: {
    flex: 1,
    padding: "3px 4px",
    border: "1px solid transparent",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 13,
  },

  primaryBtn: {
    width: "100%",
    marginTop: 10,
    padding: "10px 13px",
    border: "1px solid rgba(255,255,255,0.28)",
    borderRadius: 14,
    background: "var(--accent-gradient)",
    color: "#ffffff",
    boxShadow: "var(--shadow-accent)",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 700,
  },
  primaryBtnSmall: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "10px 13px",
    border: "1px solid rgba(255,255,255,0.28)",
    borderRadius: 14,
    background: "var(--accent-gradient)",
    color: "#ffffff",
    boxShadow: "var(--shadow-accent)",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  ghostBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "8px 11px",
    border: "1px solid var(--control-border)",
    borderRadius: 12,
    background: "rgba(255,255,255,0.48)",
    color: "var(--text-primary)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.66)",
    cursor: "pointer",
    fontSize: 12,
  },
  dangerBtn: {
    padding: "8px 11px",
    border: "1px solid rgba(190,18,60,0.22)",
    borderRadius: 12,
    background: "rgba(255,241,242,0.7)",
    color: "#9f1239",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.7)",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 700,
  },
  iconBtn: {
    display: "inline-grid",
    placeItems: "center",
    padding: "7px 9px",
    border: "1px solid var(--control-border)",
    borderRadius: 11,
    background: "rgba(255,255,255,0.5)",
    color: "var(--text-secondary)",
    cursor: "pointer",
  },

  taskRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "11px 13px",
    border: "1px solid var(--control-border)",
    borderRadius: 16,
    background: "var(--glass-control)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.62)",
  },
  dragRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "11px 13px",
    border: "1px solid var(--control-border)",
    borderRadius: 16,
    background: "var(--glass-control)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.62)",
  },
  dragHandle: {
    width: 24,
    display: "inline-grid",
    placeItems: "center",
    color: "var(--text-faint)",
    cursor: "grab",
    userSelect: "none",
  },
  moveButtons: { display: "flex", gap: 5 },
  moveBtn: {
    width: 30,
    height: 30,
    padding: 0,
    display: "inline-grid",
    placeItems: "center",
    border: "1px solid var(--control-border)",
    borderRadius: 10,
    background: "rgba(255,255,255,0.5)",
    color: "var(--text-secondary)",
    cursor: "pointer",
  },

  notesLayout: {
    display: "grid",
    gridTemplateColumns: "minmax(260px, 0.8fr) minmax(0, 1.4fr)",
    gap: 16,
    alignItems: "start",
  },
  noteList: {
    maxHeight: 560,
    marginTop: 12,
    display: "flex",
    flexDirection: "column",
    gap: 9,
    overflowY: "auto",
  },
  noteCard: {
    width: "100%",
    padding: 13,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    border: "1px solid var(--control-border)",
    borderRadius: 16,
    background: "var(--glass-control)",
    color: "var(--text-primary)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.62)",
    cursor: "pointer",
    textAlign: "left",
  },
  noteCardActive: {
    borderColor: "rgba(150,38,38,0.34)",
    background: "rgba(255,244,247,0.76)",
    boxShadow:
      "0 8px 24px rgba(111,29,53,0.1), inset 0 1px 0 rgba(255,255,255,0.74)",
  },
  noteCardTop: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  noteCardTitle: {
    overflow: "hidden",
    fontSize: 13,
    fontWeight: 720,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  notePreview: {
    width: "100%",
    display: "block",
    overflow: "hidden",
    color: "var(--text-secondary)",
    fontSize: 12,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  noteDate: { color: "var(--text-muted)", fontSize: 11 },
  noteEditor: { display: "flex", flexDirection: "column", gap: 10 },
  fieldLabel: { color: "var(--text-secondary)", fontSize: 12, fontWeight: 680 },
  noteTextarea: {
    width: "100%",
    minHeight: 260,
    padding: 13,
    border: "1px solid var(--control-border)",
    borderRadius: 16,
    outline: "none",
    resize: "vertical",
    background: "var(--glass-control-strong)",
    color: "var(--text-primary)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.68)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    fontSize: 13,
    lineHeight: 1.6,
  },
  noteActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  noteMeta: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 8,
    color: "var(--text-muted)",
    fontSize: 11,
  },
  emptyState: {
    minHeight: 180,
    padding: 20,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    textAlign: "center",
  },
  emptyIcon: {
    width: 48,
    height: 48,
    display: "inline-grid",
    placeItems: "center",
    border: "1px solid var(--glass-highlight)",
    borderRadius: 16,
    background: "rgba(255,255,255,0.44)",
    color: "var(--text-muted)",
    boxShadow: "0 10px 26px rgba(75,49,91,0.1), inset 0 1px 0 rgba(255,255,255,0.7)",
  },

  boardTabs: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 12 },
  tabBtn: {
    padding: "8px 11px",
    border: "1px solid var(--control-border)",
    borderRadius: 999,
    background: "rgba(255,255,255,0.48)",
    color: "var(--text-primary)",
    cursor: "pointer",
    fontSize: 12,
  },
  tabBtnActive: {
    border: "1px solid rgba(255,255,255,0.28)",
    background: "var(--accent-gradient)",
    color: "#ffffff",
    boxShadow: "var(--shadow-accent)",
  },
};
